name: CI Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        ports:
          - 80:80
          - 8080:8080
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker images
        run: docker-compose -f docker-compose.yml build

      - name: Start Docker containers
        run: docker-compose -f docker-compose.yml up -d

      - name: Run tests
        run: |
          sleep 30
          curl --fail http://localhost:80 || exit 1
          curl --fail http://localhost:8080/api/health || exit 1

      - name: Stop Docker containers
        run: docker-compose -f docker-compose.yml down

      - name: Push Docker images to Nexus
        run: |
          docker tag frontend:latest nexus.example.com/repository/docker-repo/frontend:latest
          docker tag backend:latest nexus.example.com/repository/docker-repo/backend:latest
          docker push nexus.example.com/repository/docker-repo/frontend:latest
          docker push nexus.example.com/repository/docker-repo/backend:latest
        env:
          DOCKER_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
