name: CI Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker images
        run: docker-compose -f docker-compose.yml build

      - name: Start Docker containers
        run: docker-compose -f docker-compose.yml up -d

      - name: Run tests
        run: |
          # Add any commands to test your services here
          echo "Running tests..."
          # Example: curl -f http://localhost:3000 || exit 1

      - name: Stop Docker containers
        run: docker-compose -f docker-compose.yml down

      - name: Push Docker images to Docker Hub
        run: |
          docker tag react-java0mysql_frontend ${{ secrets.DOCKER_USERNAME }}/react-java0mysql_frontend:latest
          docker tag react-java0mysql_backend ${{ secrets.DOCKER_USERNAME }}/react-java0mysql_backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/react-java0mysql_frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/react-java0mysql_backend:latest
